[package]
name = "object-path"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
object_store = { version = "0.9.0", features = ["http", "aws", "azure", "gcp"] }
tokio = { version = "1.35.0", features = ["full"]}
bytecount = "0.6.7"
bytes = "1.5.0"
url = "2.5.0"
futures-util = { version = "0.3.29"}
thiserror = "1.0.56"

[dev-dependencies]
rand = "0.8.5"
anyhow = "1.0.79"
